### ISSUE TITLE
Colors should be pleasant to the eye

### ISSUE THREAD

**Issue by TracyReithSW** [TracyReithSW/practice#2]
Good god, those colors are hideous. Change them.

**Comment by TracyReithSW** [comment]
## TODO
* [ ] Refer to [Material colors](https://material.io/guidelines/style/color.html#color-color-palette)
* [ ] Select new colors that aren't ugly
* [ ] Implement new colors

🍰
